// Code generated by encore. DO NOT EDIT.

package webshop

import (
	"context"
	"net/http"
)

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

// ServeShopStatic serves the frontend for web shop.
func ServeShopStatic(ctx context.Context, path string, req *http.Request) (*http.Response, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return nil, nil
}

// ServeShopBackend serves web shop backend
func ServeShopBackend(ctx context.Context, path string, req *http.Request) (*http.Response, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return nil, nil
}

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface{}
