// Code generated by encore. DO NOT EDIT.

package emailer

import (
	"context"
	messages "encore.app/pkg/messages"
)

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

// HandleServerProvisioned sends an email after a server has been provisioned
func HandleServerProvisioned(ctx context.Context, p *messages.ServerProvisioned) error {
	// The implementation is elided here, and generated at compile-time by Encore.
	return nil
}

// HandleServerTerminated sends an email after a server has been terminated
func HandleServerTerminated(ctx context.Context, p *messages.ServerTerminated) error {
	// The implementation is elided here, and generated at compile-time by Encore.
	return nil
}

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface {
	// HandleServerProvisioned sends an email after a server has been provisioned
	HandleServerProvisioned(ctx context.Context, p *messages.ServerProvisioned) error

	// HandleServerTerminated sends an email after a server has been terminated
	HandleServerTerminated(ctx context.Context, p *messages.ServerTerminated) error
}
