// Code generated by encore. DO NOT EDIT.

package checkout

import (
	"context"
	server "encore.app/checkout/server"
	"net/http"
)

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

// RequestServer requests a new server
func RequestServer(ctx context.Context, p *RequestServerReq) (*RequestServerResp, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*RequestServerResp)(nil), nil
}

func PaymentCallback(ctx context.Context, req *http.Request) (*http.Response, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return nil, nil
}

// RegisterServerPayment marks server as paid
func RegisterServerPayment(ctx context.Context, p *RegisterServerPaymentReq) error {
	// The implementation is elided here, and generated at compile-time by Encore.
	return nil
}

func ServerDetails(ctx context.Context, id uint64) (*server.Server, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*server.Server)(nil), nil
}

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface {
	// RequestServer requests a new server
	RequestServer(ctx context.Context, p *RequestServerReq) (*RequestServerResp, error)

	// RegisterServerPayment marks server as paid
	RegisterServerPayment(ctx context.Context, p *RegisterServerPaymentReq) error

	ServerDetails(ctx context.Context, id uint64) (*server.Server, error)
}
